package com.winston.mapper;

import com.winston.entity.ElIcon;
import com.winston.entity.ElIconExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ElIconMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_icon
     *
     * @mbg.generated
     */
    long countByExample(ElIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_icon
     *
     * @mbg.generated
     */
    int deleteByExample(ElIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_icon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_icon
     *
     * @mbg.generated
     */
    int insert(ElIcon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_icon
     *
     * @mbg.generated
     */
    int insertSelective(ElIcon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_icon
     *
     * @mbg.generated
     */
    List<ElIcon> selectByExample(ElIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_icon
     *
     * @mbg.generated
     */
    ElIcon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_icon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ElIcon record, @Param("example") ElIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_icon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ElIcon record, @Param("example") ElIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_icon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ElIcon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_icon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ElIcon record);
}