package com.winston.mapper;

import com.winston.entity.GroupRolePermission;
import com.winston.entity.GroupRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_permission
     *
     * @mbg.generated
     */
    long countByExample(GroupRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_permission
     *
     * @mbg.generated
     */
    int deleteByExample(GroupRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_permission
     *
     * @mbg.generated
     */
    int insert(GroupRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_permission
     *
     * @mbg.generated
     */
    int insertSelective(GroupRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_permission
     *
     * @mbg.generated
     */
    List<GroupRolePermission> selectByExample(GroupRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GroupRolePermission record, @Param("example") GroupRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GroupRolePermission record, @Param("example") GroupRolePermissionExample example);
}