package com.winston.mapper;

import com.winston.entity.ProjectLog;
import com.winston.entity.ProjectLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_log
     *
     * @mbg.generated
     */
    long countByExample(ProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_log
     *
     * @mbg.generated
     */
    int deleteByExample(ProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_log
     *
     * @mbg.generated
     */
    int insert(ProjectLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_log
     *
     * @mbg.generated
     */
    int insertSelective(ProjectLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_log
     *
     * @mbg.generated
     */
    List<ProjectLog> selectByExample(ProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_log
     *
     * @mbg.generated
     */
    ProjectLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProjectLog record, @Param("example") ProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProjectLog record, @Param("example") ProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectLog record);
}