package com.winston.entity;

import java.io.Serializable;

public class ElIcon implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_icon.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_icon.icon_class
     *
     * @mbg.generated
     */
    private String iconClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table el_icon
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_icon.id
     *
     * @return the value of el_icon.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_icon.id
     *
     * @param id the value for el_icon.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_icon.icon_class
     *
     * @return the value of el_icon.icon_class
     *
     * @mbg.generated
     */
    public String getIconClass() {
        return iconClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_icon.icon_class
     *
     * @param iconClass the value for el_icon.icon_class
     *
     * @mbg.generated
     */
    public void setIconClass(String iconClass) {
        this.iconClass = iconClass == null ? null : iconClass.trim();
    }
}