package com.winston.entity;

import java.io.Serializable;

public class GroupUserProject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user_project.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user_project.staff_id
     *
     * @mbg.generated
     */
    private Integer staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user_project.cli_id
     *
     * @mbg.generated
     */
    private Integer cliId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user_project.pro_id
     *
     * @mbg.generated
     */
    private Integer proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_user_project
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user_project.group_id
     *
     * @return the value of group_user_project.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user_project.group_id
     *
     * @param groupId the value for group_user_project.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user_project.staff_id
     *
     * @return the value of group_user_project.staff_id
     *
     * @mbg.generated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user_project.staff_id
     *
     * @param staffId the value for group_user_project.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user_project.cli_id
     *
     * @return the value of group_user_project.cli_id
     *
     * @mbg.generated
     */
    public Integer getCliId() {
        return cliId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user_project.cli_id
     *
     * @param cliId the value for group_user_project.cli_id
     *
     * @mbg.generated
     */
    public void setCliId(Integer cliId) {
        this.cliId = cliId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user_project.pro_id
     *
     * @return the value of group_user_project.pro_id
     *
     * @mbg.generated
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user_project.pro_id
     *
     * @param proId the value for group_user_project.pro_id
     *
     * @mbg.generated
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }
}