package com.winston.entity;

import java.io.Serializable;

public class GroupRolePermission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role_permission.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role_permission.per_id
     *
     * @mbg.generated
     */
    private Integer perId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role_permission.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_role_permission
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_role_permission.role_id
     *
     * @return the value of group_role_permission.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_role_permission.role_id
     *
     * @param roleId the value for group_role_permission.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_role_permission.per_id
     *
     * @return the value of group_role_permission.per_id
     *
     * @mbg.generated
     */
    public Integer getPerId() {
        return perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_role_permission.per_id
     *
     * @param perId the value for group_role_permission.per_id
     *
     * @mbg.generated
     */
    public void setPerId(Integer perId) {
        this.perId = perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_role_permission.group_id
     *
     * @return the value of group_role_permission.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_role_permission.group_id
     *
     * @param groupId the value for group_role_permission.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}