package com.winston.entity;

import lombok.Data;

import java.io.Serializable;

/**
 * @ClassName GroupRolePermissionDTO
 * @Author: Winston
 * @Description: TODO
 * @Date:Create：in 2020/1/7 15:08
 * @Version：
 */
@Data
public class GroupRolePermissionDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role_permission.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role_permission.per_id
     *
     * @mbg.generated
     */
    private Integer[] perId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role_permission.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_role_permission
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}
