package com.winston.entity;

import java.io.Serializable;

public class LogInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.result_type
     *
     * @mbg.generated
     */
    private String resultType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.log_type
     *
     * @mbg.generated
     */
    private String logType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.ip_address
     *
     * @mbg.generated
     */
    private String ipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.operatordesc
     *
     * @mbg.generated
     */
    private String operatordesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.id
     *
     * @return the value of log_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.id
     *
     * @param id the value for log_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.user_id
     *
     * @return the value of log_info.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.user_id
     *
     * @param userId the value for log_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.result_type
     *
     * @return the value of log_info.result_type
     *
     * @mbg.generated
     */
    public String getResultType() {
        return resultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.result_type
     *
     * @param resultType the value for log_info.result_type
     *
     * @mbg.generated
     */
    public void setResultType(String resultType) {
        this.resultType = resultType == null ? null : resultType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.log_type
     *
     * @return the value of log_info.log_type
     *
     * @mbg.generated
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.log_type
     *
     * @param logType the value for log_info.log_type
     *
     * @mbg.generated
     */
    public void setLogType(String logType) {
        this.logType = logType == null ? null : logType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.create_time
     *
     * @return the value of log_info.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.create_time
     *
     * @param createTime the value for log_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.ip_address
     *
     * @return the value of log_info.ip_address
     *
     * @mbg.generated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.ip_address
     *
     * @param ipAddress the value for log_info.ip_address
     *
     * @mbg.generated
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.operatordesc
     *
     * @return the value of log_info.operatordesc
     *
     * @mbg.generated
     */
    public String getOperatordesc() {
        return operatordesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.operatordesc
     *
     * @param operatordesc the value for log_info.operatordesc
     *
     * @mbg.generated
     */
    public void setOperatordesc(String operatordesc) {
        this.operatordesc = operatordesc == null ? null : operatordesc.trim();
    }
}