package com.winston.entity;

import lombok.Data;

import java.io.Serializable;

/**
 * @ClassName ProjectDTO
 * @Author: Winston
 * @Description: TODO
 * @Date:Create：in 2020/1/10 11:47
 * @Version：
 */
@Data
public class ProjectDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pro_name
     *
     * @mbg.generated
     */
    private String proName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pro_desc
     *
     * @mbg.generated
     */
    private String proDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pic_id
     *
     * @mbg.generated
     */
    private Integer picId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.priority
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.start_time
     *
     * @mbg.generated
     */
    private Long startTime;

    private String startTimeFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.end_time
     *
     * @mbg.generated
     */
    private Long endTime;

    private String endTimeFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.rel_end_time
     *
     * @mbg.generated
     */
    private Long relEndTime;

    private String relEndTimeFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pro_schedule
     *
     * @mbg.generated
     */
    private Integer proSchedule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.state
     *
     * @mbg.generated
     */
    private Integer state;

    private Integer groupId;

    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}
