package com.winston.entity;

import java.io.Serializable;

public class Project implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pro_name
     *
     * @mbg.generated
     */
    private String proName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pro_desc
     *
     * @mbg.generated
     */
    private String proDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pic_id
     *
     * @mbg.generated
     */
    private Integer picId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.priority
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.start_time
     *
     * @mbg.generated
     */
    private Long startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.end_time
     *
     * @mbg.generated
     */
    private Long endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.rel_end_time
     *
     * @mbg.generated
     */
    private Long relEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pro_schedule
     *
     * @mbg.generated
     */
    private Integer proSchedule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pro_name
     *
     * @return the value of project.pro_name
     *
     * @mbg.generated
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pro_name
     *
     * @param proName the value for project.pro_name
     *
     * @mbg.generated
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pro_desc
     *
     * @return the value of project.pro_desc
     *
     * @mbg.generated
     */
    public String getProDesc() {
        return proDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pro_desc
     *
     * @param proDesc the value for project.pro_desc
     *
     * @mbg.generated
     */
    public void setProDesc(String proDesc) {
        this.proDesc = proDesc == null ? null : proDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pic_id
     *
     * @return the value of project.pic_id
     *
     * @mbg.generated
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pic_id
     *
     * @param picId the value for project.pic_id
     *
     * @mbg.generated
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.priority
     *
     * @return the value of project.priority
     *
     * @mbg.generated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.priority
     *
     * @param priority the value for project.priority
     *
     * @mbg.generated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.start_time
     *
     * @return the value of project.start_time
     *
     * @mbg.generated
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.start_time
     *
     * @param startTime the value for project.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.end_time
     *
     * @return the value of project.end_time
     *
     * @mbg.generated
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.end_time
     *
     * @param endTime the value for project.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.rel_end_time
     *
     * @return the value of project.rel_end_time
     *
     * @mbg.generated
     */
    public Long getRelEndTime() {
        return relEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.rel_end_time
     *
     * @param relEndTime the value for project.rel_end_time
     *
     * @mbg.generated
     */
    public void setRelEndTime(Long relEndTime) {
        this.relEndTime = relEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pro_schedule
     *
     * @return the value of project.pro_schedule
     *
     * @mbg.generated
     */
    public Integer getProSchedule() {
        return proSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pro_schedule
     *
     * @param proSchedule the value for project.pro_schedule
     *
     * @mbg.generated
     */
    public void setProSchedule(Integer proSchedule) {
        this.proSchedule = proSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.parent_id
     *
     * @return the value of project.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.parent_id
     *
     * @param parentId the value for project.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.state
     *
     * @return the value of project.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.state
     *
     * @param state the value for project.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}